app {

  name = "Retail Data Platform"

}

spark {

  master = "local[*]"

  appName = "Retail Data Platform"

}

input {

  orders = "data/input/orders.csv"

  customers = "data/input/customers.csv"

}

output {

  path = "data/output"

}