app {
  name = "Retail Data Platform"
}

spark {
  master = "local[*]"
  appName = "Retail Data Platform"
}

paths {
  input = "data/input"
  output = "data/output"
  invalid = "data/invalid"
  archive = "data/archive"
}

files {
  customer = "data/customers.csv"
  validOutput = "output/valid"
  invalidOutput = "output/invalid"
}